let defaultLang = "en"
function changeLanguage() {

    let en = [
        ["summary", "Summary"],
        ["gradess", "Grades"],
        ["experiences", "Experience"],
        ["projectss", "Projects"],
        ["contactss", "Contacts"],
        ["idAge", "My name is Geoffrey, Im 22Years old."],
        ["developper", "French Developer.<span\n" + "class=\"frenchFlag rounded-pill flagInDesc\"></span>"],
        ["CVHere", "Take a look at my CV here <a href=\"ext/img/projects/Hallier_Geoffrey.pdf\"><i\n" + "class=\"fa-solid fa-download\"></i></a>"],
        ["mynameTop", "My name is Geoffrey Hallier."],
        ["tagDev", "Developer"],
        ["socialsLinks", "Socials links <i class=\"fa-solid fa-arrow-turn-up\"></i>"],
        ["aboutme", "A bit about me :"],
        ["languagesispeak", "I speak french and english."],
        ["studying", "Currently studying at Epitech Lille."],
        ["ilandedin", "I landed in Web Developpement in 2020."],
        ["gameDev", "I was in game developpement from 2017 to 2020."],
        ["stilldoing", "Still doing games scripting during my free time."],
        ["proudof", "Im proud of my work to be honest."],
        ["jobsearch", "Im actually in job search."],
        ["ineverstop", "I never stop learning and that's what i like!"],
        ["oldDev", "And im currently in developpement for over 8 years...\n" + "<div class=\"CMDlike\"></div>"],
        ["duringThese", "During theses 8 years what i learn :"],
        ["gradeandActv", "What's my grades and activities ?"],
        ["gradesobtn", "Current grades"],
        ["brevet", "Brevet"],
        ["acquiredin2015", "Acquired in 2015."],
        ["at15yo", "At 15 Years old"],
        ["atlenouv", "At Le-Nouvion-en-Thierache."],
        ["inAisne", "In the Aisne departement."],
        ["BEP", "BEP Machining technician."],
        ["acquis202", "Acquired in 2020."],
        ["at20yo", "At 20 years old."],
        ["athirson", "At Hirson."],
        ["inaisnetoo", "In the Aisne departement."],
        ["BAC", "BAC +2"],
        ["inprocess", "In the process of acquiring"],
        ["at22", "At 22 years old."],
        ["webAc", "At Web@cademie."],
        ["atlille", "At Lille."],
        ["actidone", "Activities done"],
        ["orderprepare", "Order preparer."],
        ["2months", "2 Months each summer for work."],
        ["20182021", "From 2018 to 2021."],
        ["aisneagain", "In the Aisne departement."],
        ["techicalmaint", "Technical maintenance."],
        ["3monthseach", "3 Months each years for school."],
        ["2018202111", "From 2018 to 2021."],
        ["aisnepower", "In the Aisne departement."],
        ["waletweb", "Website and wallet development."],
        ["augt2021", "From august 2021 to september 2023."],
        ["forschool", "For school learning."],
        ["lilleagain", "At Lille."],
        ["myexperience", "My experience"],
        ["fwsprojectsC", "Done fews projects working with HEX in RTE for my console (PS3)."],
        ["notlearnedC", "Not learned so much to be honest."],
        ["quitlimited", "Quit limited in possibilities on theses projects..."],
        ["done1C++", "Done 1 project in C++, like C# it was for my console."],
        ["notlearnedmuchtoo", "Not learned so much too."],
        ["veryoldpro", "It's very old projects i don't remember exactly."],
        ["workedonmany", "Worked on many projects."],
        ["reallylove", "Really love this language."],
        ["worked50%", "Worked 50% in vanilla HTML and 50% with Bootstrap."],
        ["jsiscool", "JavaScript is really cool."],
        ["notstoppintolearn", "Im not stopping to learn Javascript."],
        ["jslove", "JavaScript is one of my favorite language."],
        ["sqlhard", "Hard to take in hand at the beginning but really logical."],
        ["lessimple", "Simple language with less simple code."],
        ["atleast", "At least we have really good Docs."],
        ["partofgit", "Github is a part of the development that why im putting it here."],
        ["iknowhowto", "I know how to work in team on GitHub."],
        ["needtoworkonbig", "I just need to work on a bigger team to see others results."],
        ["gscSC", "GSC for Game Script Compiler."],
        ["makemanygsc", "Make many projects with GSC."],
        ["funnyandintersting", "It was very fun and interesting but nothing concrete with this language."],
        ["sqfmyreal", "SQF, my first real love."],
        ["languageforbohm", "It's a language make for Bohemia games."],
        ["similartojs", "Similar to JS (for me)."],
        ["donemanyprojects", "Done many many projects for my self or for a german company."],
        ["htmlwithoutcss", "HTML without CSS ? No way."],
        ["reallyenjoy", "Really enjoying connect things together."],
        ["loveworkcss", "Love working on CSS."],
        ["phpstrange", "PHP... this strange language."],
        ["tbhphp", "To be honest is one of the language where i don't enjoy working on."],
        ["betweenphp", "When i have the choice between PHP and JS, im surely taking JS."],
        ["reallygoodframe", "Really interesting framework."],
        ["workingreact", "Love working with REACT , need more learning to be better."],
        ["needmorelearn", "I need to learn more about REACT but i will surely learn more about it!"],
        ["startedfirstBS", "Started my first project with BootStrap and really loved it."],
        ["bsiscool", "Bootstrap is awesome to use but its cool too to make project without."],
        ["iusewithout", "I use bootstrap without any problems."],
        ["myprojects", "My projects."],
        ["twitterremake", "Twitter Remake."],
        ["interestingtwit", "Interesting project !"],
        ["prjt1month", "Project duration was 1 month."],
        ["madethem4", "Made with team of 4."],
        ["frntcollegue", "I made the front with a collegue."],
        ["otherbackend", "Others members done the back-end."],
        ["idonesomeJS", "I done some JavaScript too."],
        ["gitseenTwt", "<i\n" + "class=\"fa-brands fa-github\"></i>  Seen on Github"],
        ["handmade", "Handmade project."],
        ["donein3days", "Done this project in 3 days."],
        ["madealone", "Made alone."],
        ["madeBS", "Made with Bootstrap."],
        ["somecss", "Some CSS and JavaScript too."],
        ["funtodoport", "It was really fun to do."],
        ["gitport", "<i\n" + "class=\"fa-brands fa-github\"></i> Seen on Github"],
        ["inprogweb3", "In progress webextension project."],
        ["strt1ya", "Project started 1 years ago."],
        ["madeof3", "Made with team of 3."],
        ["fontwithcllg", "I made the front with a collegue."],
        ["othersmember", "Others members give us idea and do the communication."],
        ["idolots", "I do HTML,CSS,JS and using chartJS."],
        ["gitweb3", "<i\n" + "class=\"fa-brands fa-github\"></i> Seen on Github"],
        ["irc", "First IRC project."],
        ["doneinfews", "Done this project in fews days."],
        ["madealonetoo", "Made alone."],
        ["madewithirc", "Made with NodeJS,Express,Sequelizer."],
        ["somecssect", "Some CSS and JavaScript too."],
        ["iwit", "It was interesting."],
        ["gitirc", "<i\n" + "class=\"fa-brands fa-github\"></i> Seen on Github"],
        ["howtocontact", "How to contact me ?"],
        ["mailhere", "You can contact me by mail here <i class=\"fa-solid fa-arrow-down\"></i>?"],
        ["orbythis", ">Or you can contact me with your own email,in this case click here to copy my email : <i\n" + "class=\"fa-solid fa-envelope\" onclick=\"showAlert(this.id)\" id=\"emailcontact\"></i>"],
        ["socialsNetowrkBtm", "My socials network"],
        ["mymail", "My mail"],
        ["share", "Share"],
        ["fftc", "Feel free to contact me on any of these network."],
    ]

    let fr = [
        ["summary", "Resumé"],
        ["gradess", "Parcours"],
        ["experiences", "Experience"],
        ["projectss", "Projets"],
        ["contactss", "Contacts"],
        ["idAge", "Je m'appelle Geoffrey j'ai 22 ans."],
        ["developper", "Développeur Français.<span\n" + "class=\"frenchFlag rounded-pill flagInDesc\"></span>"],
        ["CVHere", "Mon CV est disponible ici <a href=\"ext/img/projects/Hallier_Geoffrey.pdf\"><i\n" + "class=\"fa-solid fa-download\"></i></a>"],
        ["mynameTop", "Je m'apelle Geoffrey Hallier."],
        ["tagDev", "Developpeur"],
        ["socialsLinks", "Réseaux sociaux <i class=\"fa-solid fa-arrow-turn-up\"></i>"],
        ["aboutme", "A propos de moi :"],
        ["languagesispeak", "Je parle Anglais & Français."],
        ["studying", "J'étudie actuellement a Epitech."],
        ["ilandedin", "J'ai atterri dans le developpement Web en 2020."],
        ["gameDev", "J'étais dans le developpement jeux-video de 2017 à 2020."],
        ["stilldoing", "Je developpe toujours dans le jeux-vidéo durant mon temps libre."],
        ["proudof", "Je suis assez fier de mon travail pour être honnête"],
        ["jobsearch", "Je recherche actuellement un travail."],
        ["ineverstop", "Je n'arrête jamais d'apprendre et j'aime sa !"],
        ["oldDev", "Je suis dans le developpement depuis 8ans...\n" + "<div class=\"CMDlike\"></div>"],
        ["duringThese", "Durant ces 8ans j'ai appris :"],
        ["gradeandActv", "Mon parcours"],
        ["gradesobtn", "Mes Diplômes"],
        ["brevet", "Brevet"],
        ["acquiredin2015", "Acquis en 2015."],
        ["at15yo", "A 15ans"],
        ["atlenouv", "A Le-Nouvion-en-Thierache."],
        ["inAisne", "Dans le departement de l'Aisne."],
        ["BEP", "BEP technicien d'usinage."],
        ["acquis202", "Acquis en 2020."],
        ["at20yo", "A 20 ans."],
        ["athirson", "A Hirson."],
        ["inaisnetoo", "Dans le departement de l'Aisne."],
        ["BAC", "BAC +2"],
        ["inprocess", "En cours."],
        ["at22", "A 22ans."],
        ["webAc", "A la Web@cademie."],
        ["atlille", "A Lille."],
        ["actidone", "Postes occupées"],
        ["orderprepare", "Préparateur de commandes."],
        ["2months", "2 Mois chaque été."],
        ["20182021", "De 2018 à 2021."],
        ["aisneagain", "Dans le departement de l'Aisne."],
        ["techicalmaint", "Technicien de maintenance."],
        ["3monthseach", "3 Mois par an pour mon lycée."],
        ["2018202111", "De 2018 à 2021."],
        ["aisnepower", "Dans le departement de l'Aisne."],
        ["waletweb", "Developpement du site et du wallet."],
        ["augt2021", "De Août 2021 à septembre 2023."],
        ["forschool", "Pour de l'apprentisage."],
        ["lilleagain", "A Lille."],
        ["myexperience", "Mon experience"],
        ["fwsprojectsC", "J'ai fait quelques projets avec des HEX en RTE sur console (PS3)."],
        ["notlearnedC", "Je n'ai pas appris enormément malheureusement."],
        ["quitlimited", "J'étais vraiment limité sur ces projects..."],
        ["done1C++", "J'ai fait 1 projet C++, c'étais pour console aussi."],
        ["notlearnedmuchtoo", "Je n'ai pas appris enormément aussi."],
        ["veryoldpro", "Ce sont de vieux projets que je ne posséde plus."],
        ["workedonmany", "J'ai travaillé sur beaucoup de projects."],
        ["reallylove", "J'aime enormément ce language."],
        ["worked50%", "J'ai travaillé 50% en vanilla et 50% avec Bootstrap."],
        ["jsiscool", "Le JavaScript c'est vraiment cool."],
        ["notstoppintolearn", "Je n'arrête jamais d'apprendre le Javascript."],
        ["jslove", "Le JavaScript est un de mes languages favoris."],
        ["sqlhard", "Dur a prendre en main mais logique par la suite."],
        ["lessimple", "Language simple avec du code moins simple."],
        ["atleast", "Mais il y'a une super doc."],
        ["partofgit", "Github fait parti du developpement c'est pour sa que je le met ici."],
        ["iknowhowto", "Je sais travaillé en équipe sur GitHub."],
        ["needtoworkonbig", "J'ai juste besoin de travaillé dans une plus grosse teams pour aller plus loin."],
        ["gscSC", "GSC pour Game Script Compiler."],
        ["makemanygsc", "J'ai fait pas mal de GSC."],
        ["funnyandintersting", "C'etais un language sympa mais rien de concret avec celui-ci."],
        ["sqfmyreal", "SQF, mon premier vrai amour."],
        ["languageforbohm", "C'est un language pour les jeux Bohemia."],
        ["similartojs", "Similaire au JS (pour moi)."],
        ["donemanyprojects", "J'ai fait pas mal de project personnel et d'autres pour des entreprises."],
        ["htmlwithoutcss", "HTML sans CSS ? Improbable."],
        ["reallyenjoy", "J'adore assemblé les élements entre eux."],
        ["loveworkcss", "J'adore travaillé sur du CSS."],
        ["phpstrange", "PHP... ce language étrange."],
        ["tbhphp", "Pour être honnéte c'est un  des languages que j'aime le moins."],
        ["betweenphp", "Quand j'ai le choix je préfére travaillé avec du JavaScript."],
        ["reallygoodframe", "Framework intéressant."],
        ["workingreact", "J'aime bien travaillé avec React, mais je doit faire plsu de projets pour progresser."],
        ["needmorelearn", "J'ai besoin d'apprendre plus en React !"],
        ["startedfirstBS", "J'ai fait mon prmier projet avec BootStrap et c'étais vraiment super."],
        ["bsiscool", "Bootstrap est sympa a utilisé mais c'est aussi cool de faire des projets sans."],
        ["iusewithout", "J'utilise Bootstrap sans aucuns soucis."],
        ["myprojects", "Mes projets."],
        ["twitterremake", "Création de Twitter."],
        ["interestingtwit", "Projet intéressant!"],
        ["madethem4", "Projet realisé a 4."],
        ["frntcollegue", "J'ai fait le font avec un collègue."],
        ["otherbackend", "Les autres membres ont fait le back-end."],
        ["idonesomeJS", "J'ai fait du JavaScript aussi."],
        ["gitseenTwt", "<i\n" + "class=\"fa-brands fa-github\"></i> Voir sur Github"],
        ["handmade", "Projet fait main."],
        ["donein3days", "Projet réalise en 3 jours."],
        ["madealone", "Realisé seul."],
        ["madeBS", "Fait avec Bootstrap."],
        ["somecss", "Pas mal de CSS et un peu de JS."],
        ["funtodoport", "C'étais vraiment sympa a faire."],
        ["gitport", "<i\n" + "class=\"fa-brands fa-github\"></i> Voir sur Github"],
        ["inprogweb3", "Projet extension Web3 en cours."],
        ["strt1ya", "Projet commencé il y'a 1 an."],
        ["madeof3", "Fait par une team de 3."],
        ["fontwithcllg", "Je fait le front avec un collègue."],
        ["othersmember", "Les autres membres nous donnent des idées et font de la communication."],
        ["idolots", "Je fait du HTML,CSS,JS et j'utilise chartJS."],
        ["gitweb3", "<i\n" + "class=\"fa-brands fa-github\"></i> Voir sur Github"],
        ["irc", "Premier projet IRC."],
        ["doneinfews", "Projet realisée en quelques jours."],
        ["madealonetoo", "Realisé seul."],
        ["madewithirc", "Fait avec NodeJS,Express,Sequelizer."],
        ["somecssect", "Avec du CSS et du JS aussi."],
        ["iwit", "C'étais intéressant."],
        ["gitirc", "<i\n" + "class=\"fa-brands fa-github\"></i> Voir sur Github"],
        ["howtocontact", "Comment me contacté ?"],
        ["mailhere", "Vous pouvez me contacter par email ici <i class=\"fa-solid fa-arrow-down\"></i>"],
        ["orbythis", "Ou vous pouvez me contactez depuis votre boîte mail en cliquant ici pour copier mon email : <i\n" + "class=\"fa-solid fa-envelope\" onclick=\"showAlert(this.id)\" id=\"emailcontact\"></i>"],
        ["socialsNetowrkBtm", "Mes réseaux sociaux"],
        ["mymail", "Mon email"],
        ["share", "Partager"],
        ["fftc", "Libre a vous de me contacter sur n'importe lequel de ces réseaux."],


    ]

    console.log(defaultLang)

    if (defaultLang === "en"){
        defaultLang = "fr"
        for (var i = 0; i < fr.length; i++) {
            let act = document.getElementById(fr[i][0])
            act.innerHTML = fr[i][1]
        }
    } else {
        defaultLang = "en"
        for (var i = 0; i < en.length; i++) {
            let act = document.getElementById(en[i][0])
            act.innerHTML = en[i][1]
        }
    }

}